// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// tabloToR_eliminate_blocks
Rcpp::List tabloToR_eliminate_blocks(SEXP matrix_sexp, Rcpp::NumericVector rhs, Rcpp::IntegerVector row_group, Rcpp::IntegerVector column_group, int n_groups, double pivot_tolerance);
RcppExport SEXP _tabloToR_tabloToR_eliminate_blocks(SEXP matrix_sexpSEXP, SEXP rhsSEXP, SEXP row_groupSEXP, SEXP column_groupSEXP, SEXP n_groupsSEXP, SEXP pivot_toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type matrix_sexp(matrix_sexpSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rhs(rhsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type row_group(row_groupSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type column_group(column_groupSEXP);
    Rcpp::traits::input_parameter< int >::type n_groups(n_groupsSEXP);
    Rcpp::traits::input_parameter< double >::type pivot_tolerance(pivot_toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(tabloToR_eliminate_blocks(matrix_sexp, rhs, row_group, column_group, n_groups, pivot_tolerance));
    return rcpp_result_gen;
END_RCPP
}
// tabloToR_reconstruct_blocks
Rcpp::NumericVector tabloToR_reconstruct_blocks(SEXP matrix_sexp, Rcpp::NumericVector rhs, Rcpp::NumericVector reduced_solution, Rcpp::IntegerVector row_group, Rcpp::IntegerVector column_group, int n_groups, double pivot_tolerance);
RcppExport SEXP _tabloToR_tabloToR_reconstruct_blocks(SEXP matrix_sexpSEXP, SEXP rhsSEXP, SEXP reduced_solutionSEXP, SEXP row_groupSEXP, SEXP column_groupSEXP, SEXP n_groupsSEXP, SEXP pivot_toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type matrix_sexp(matrix_sexpSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rhs(rhsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type reduced_solution(reduced_solutionSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type row_group(row_groupSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type column_group(column_groupSEXP);
    Rcpp::traits::input_parameter< int >::type n_groups(n_groupsSEXP);
    Rcpp::traits::input_parameter< double >::type pivot_tolerance(pivot_toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(tabloToR_reconstruct_blocks(matrix_sexp, rhs, reduced_solution, row_group, column_group, n_groups, pivot_tolerance));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tabloToR_tabloToR_eliminate_blocks", (DL_FUNC) &_tabloToR_tabloToR_eliminate_blocks, 6},
    {"_tabloToR_tabloToR_reconstruct_blocks", (DL_FUNC) &_tabloToR_tabloToR_reconstruct_blocks, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_tabloToR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
