# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.tabloToR_dense_lu_factor <- function(matrix) {
    .Call(`_tabloToR_tabloToR_dense_lu_factor`, matrix)
}

.tabloToR_dense_lu_solve <- function(pointer_sexp, rhs_sexp) {
    .Call(`_tabloToR_tabloToR_dense_lu_solve`, pointer_sexp, rhs_sexp)
}

.tabloToR_dense_lu_release <- function(pointer_sexp) {
    invisible(.Call(`_tabloToR_tabloToR_dense_lu_release`, pointer_sexp))
}

tabloToR_eliminate_blocks <- function(matrix_sexp, rhs, row_group, column_group, n_groups, pivot_tolerance) {
    .Call(`_tabloToR_tabloToR_eliminate_blocks`, matrix_sexp, rhs, row_group, column_group, n_groups, pivot_tolerance)
}

tabloToR_reconstruct_blocks <- function(matrix_sexp, rhs, reduced_solution, row_group, column_group, n_groups, pivot_tolerance) {
    .Call(`_tabloToR_tabloToR_reconstruct_blocks`, matrix_sexp, rhs, reduced_solution, row_group, column_group, n_groups, pivot_tolerance)
}

.tabloToR_schur_cpp_capabilities <- function() {
    .Call(`_tabloToR_tabloToR_schur_cpp_capabilities`)
}

.tabloToR_sparse_lu_solve <- function(factor_sexp, rhs_sexp) {
    .Call(`_tabloToR_tabloToR_sparse_lu_solve`, factor_sexp, rhs_sexp)
}

.tabloToR_sparse_pattern_hash <- function(matrix_sexp) {
    .Call(`_tabloToR_tabloToR_sparse_pattern_hash`, matrix_sexp)
}

.tabloToR_schur_accumulate_batch_parallel <- function(factors, left_blocks, right_blocks, direct_external_sexp, regional_positions_sexp, global_positions_sexp, batch_regions_sexp, panel_size, threads) {
    .Call(`_tabloToR_tabloToR_schur_accumulate_batch_parallel`, factors, left_blocks, right_blocks, direct_external_sexp, regional_positions_sexp, global_positions_sexp, batch_regions_sexp, panel_size, threads)
}

.tabloToR_schur_accumulate_global <- function(factors, left_blocks, right_blocks, direct_external_sexp, regional_positions_sexp, global_positions_sexp, panel_size) {
    .Call(`_tabloToR_tabloToR_schur_accumulate_global`, factors, left_blocks, right_blocks, direct_external_sexp, regional_positions_sexp, global_positions_sexp, panel_size)
}

.tabloToR_schur_accumulate_batch <- function(factors, left_blocks, right_blocks, direct_external_sexp, regional_positions_sexp, global_positions_sexp, batch_regions_sexp, panel_size, threads) {
    .Call(`_tabloToR_tabloToR_schur_accumulate_batch`, factors, left_blocks, right_blocks, direct_external_sexp, regional_positions_sexp, global_positions_sexp, batch_regions_sexp, panel_size, threads)
}

