# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tabloToR_eliminate_blocks <- function(matrix_sexp, rhs, row_group, column_group, n_groups, pivot_tolerance) {
    .Call(`_tabloToR_tabloToR_eliminate_blocks`, matrix_sexp, rhs, row_group, column_group, n_groups, pivot_tolerance)
}

tabloToR_reconstruct_blocks <- function(matrix_sexp, rhs, reduced_solution, row_group, column_group, n_groups, pivot_tolerance) {
    .Call(`_tabloToR_tabloToR_reconstruct_blocks`, matrix_sexp, rhs, reduced_solution, row_group, column_group, n_groups, pivot_tolerance)
}

